name: InstalaciÃ³n de servicios

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Agregar clave SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 127.0.1.1 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts